2025-07-05 21:39:45 | INFO     | wpc             | === Iniciando Sistema WPC ===
2025-07-05 21:39:45 | INFO     | wpc             | Conectando a base de datos...
2025-07-05 21:39:45 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 21:39:45 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 21:39:45 | ERROR    | wpc             | Error en get_all_modules: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
Traceback (most recent call last):
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2435, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\selectable.py", line 1444, in _join_condition
    raise exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'mvt' and 'mdl'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\github\WPC_Python\core\database\managers.py", line 457, in get_all_modules
    return session.query(Module).order_by(Module.OrdenEncuesta).all()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 2955, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1658, in do_init
    self._setup_join_conditions()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1896, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2322, in __init__
    self._determine_joins()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2456, in _determine_joins
    raise sa_exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2025-07-05 21:39:45 | INFO     | wpc             | Gestor de módulos inicializado con 0 módulos
2025-07-05 21:39:45 | INFO     | wpc             | Inicializando sistema de comunicación...
2025-07-05 21:39:45 | ERROR    | wpc             | Error en initialize_serial(COM1): Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
Traceback (most recent call last):
  File "C:\github\WPC_Python\core\communication\serial_comm.py", line 101, in initialize
    self.serial_port.open()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 80, in open
    self._reconfigure_port()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 194, in _reconfigure_port
    raise ValueError(
ValueError: Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
2025-07-05 21:39:45 | ERROR    | wpc             | Error en PollingManager.initialize: Error inicializando puerto serie
NoneType: None
2025-07-05 21:39:45 | ERROR    | wpc             | Error inicializando sistema de polling
2025-07-05 21:47:46 | INFO     | wpc             | === Iniciando Sistema WPC ===
2025-07-05 21:47:46 | INFO     | wpc             | Conectando a base de datos...
2025-07-05 21:47:47 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 21:47:47 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 21:47:47 | ERROR    | wpc             | Error en get_all_modules: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
Traceback (most recent call last):
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2435, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\selectable.py", line 1444, in _join_condition
    raise exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'mvt' and 'mdl'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\github\WPC_Python\core\database\managers.py", line 457, in get_all_modules
    return session.query(Module).order_by(Module.OrdenEncuesta).all()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 2955, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1658, in do_init
    self._setup_join_conditions()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1896, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2322, in __init__
    self._determine_joins()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2456, in _determine_joins
    raise sa_exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2025-07-05 21:47:47 | INFO     | wpc             | Gestor de módulos inicializado con 0 módulos
2025-07-05 21:47:47 | INFO     | wpc             | Inicializando sistema de comunicación...
2025-07-05 21:47:47 | ERROR    | wpc             | Error en initialize_serial(COM1): Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
Traceback (most recent call last):
  File "C:\github\WPC_Python\core\communication\serial_comm.py", line 101, in initialize
    self.serial_port.open()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 80, in open
    self._reconfigure_port()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 194, in _reconfigure_port
    raise ValueError(
ValueError: Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
2025-07-05 21:47:47 | ERROR    | wpc             | Error en PollingManager.initialize: Error inicializando puerto serie
NoneType: None
2025-07-05 21:47:47 | ERROR    | wpc             | Error inicializando sistema de polling
2025-07-05 21:49:44 | INFO     | wpc             | === Iniciando Sistema WPC ===
2025-07-05 21:49:44 | INFO     | wpc             | Conectando a base de datos...
2025-07-05 21:49:44 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 21:49:44 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 21:49:44 | ERROR    | wpc             | Error en get_all_modules: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
Traceback (most recent call last):
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2435, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\selectable.py", line 1444, in _join_condition
    raise exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'mvt' and 'mdl'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\github\WPC_Python\core\database\managers.py", line 457, in get_all_modules
    return session.query(Module).order_by(Module.OrdenEncuesta).all()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 2955, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1658, in do_init
    self._setup_join_conditions()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1896, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2322, in __init__
    self._determine_joins()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2456, in _determine_joins
    raise sa_exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2025-07-05 21:49:44 | INFO     | wpc             | Gestor de módulos inicializado con 0 módulos
2025-07-05 21:49:44 | INFO     | wpc             | Inicializando sistema de comunicación...
2025-07-05 21:49:44 | ERROR    | wpc             | Error en initialize_serial(COM1): Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
Traceback (most recent call last):
  File "C:\github\WPC_Python\core\communication\serial_comm.py", line 101, in initialize
    self.serial_port.open()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 80, in open
    self._reconfigure_port()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 194, in _reconfigure_port
    raise ValueError(
ValueError: Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
2025-07-05 21:49:44 | ERROR    | wpc             | Error en PollingManager.initialize: Error inicializando puerto serie
NoneType: None
2025-07-05 21:49:44 | ERROR    | wpc             | Error inicializando sistema de polling
2025-07-05 22:25:34 | INFO     | wpc             | === Iniciando Sistema WPC ===
2025-07-05 22:25:34 | INFO     | wpc             | Conectando a base de datos...
2025-07-05 22:25:34 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 22:25:34 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 22:25:34 | ERROR    | wpc             | Error en get_all_modules: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
Traceback (most recent call last):
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2435, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\selectable.py", line 1444, in _join_condition
    raise exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'mvt' and 'mdl'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\github\WPC_Python\core\database\managers.py", line 457, in get_all_modules
    return session.query(Module).order_by(Module.OrdenEncuesta).all()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 2955, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1658, in do_init
    self._setup_join_conditions()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1896, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2322, in __init__
    self._determine_joins()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2456, in _determine_joins
    raise sa_exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2025-07-05 22:25:34 | INFO     | wpc             | Gestor de módulos inicializado con 0 módulos
2025-07-05 22:25:34 | INFO     | wpc             | Inicializando sistema de comunicación...
2025-07-05 22:25:34 | ERROR    | wpc             | Error en initialize_serial(COM1): Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
Traceback (most recent call last):
  File "C:\github\WPC_Python\core\communication\serial_comm.py", line 101, in initialize
    self.serial_port.open()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 80, in open
    self._reconfigure_port()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 194, in _reconfigure_port
    raise ValueError(
ValueError: Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
2025-07-05 22:25:34 | ERROR    | wpc             | Error en PollingManager.initialize: Error inicializando puerto serie
NoneType: None
2025-07-05 22:25:34 | ERROR    | wpc             | Error inicializando sistema de polling
2025-07-05 22:26:10 | INFO     | wpc             | === Iniciando Sistema WPC ===
2025-07-05 22:26:10 | INFO     | wpc             | Conectando a base de datos...
2025-07-05 22:26:11 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 22:26:11 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 22:26:11 | ERROR    | wpc             | Error en get_all_modules: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
Traceback (most recent call last):
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2435, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\selectable.py", line 1444, in _join_condition
    raise exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'mvt' and 'mdl'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\github\WPC_Python\core\database\managers.py", line 457, in get_all_modules
    return session.query(Module).order_by(Module.OrdenEncuesta).all()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\session.py", line 2955, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 276, in __init__
    self._set_entities(entities)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\query.py", line 289, in _set_entities
    coercions.expect(
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\sql\coercions.py", line 388, in expect
    insp._post_inspect
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\util\langhelpers.py", line 1338, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2724, in _post_inspect
    self._check_configure()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1658, in do_init
    self._setup_join_conditions()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 1896, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2322, in __init__
    self._determine_joins()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\relationships.py", line 2456, in _determine_joins
    raise sa_exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Movement.module - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2025-07-05 22:26:11 | INFO     | wpc             | Gestor de módulos inicializado con 0 módulos
2025-07-05 22:26:11 | INFO     | wpc             | Inicializando sistema de comunicación...
2025-07-05 22:26:11 | ERROR    | wpc             | Error en initialize_serial(COM1): Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
Traceback (most recent call last):
  File "C:\github\WPC_Python\core\communication\serial_comm.py", line 101, in initialize
    self.serial_port.open()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 80, in open
    self._reconfigure_port()
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\serial\serialwin32.py", line 194, in _reconfigure_port
    raise ValueError(
ValueError: Unsupported value for RS485Settings.delay_before_tx: 0.01 (only None is allowed)
2025-07-05 22:26:11 | ERROR    | wpc             | Error en PollingManager.initialize: Error inicializando puerto serie
NoneType: None
2025-07-05 22:26:11 | ERROR    | wpc             | Error inicializando sistema de polling
2025-07-05 22:58:35 | INFO     | wpc             | === Iniciando Sistema WPC ===
2025-07-05 22:58:35 | INFO     | wpc             | Conectando a base de datos...
2025-07-05 22:58:35 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 22:58:35 | INFO     | wpc             | Inicializando gestor de módulos...
2025-07-05 22:58:35 | ERROR    | wpc             | Error en _load_modules_from_database: Instance <Module at 0x1dde929e510> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Traceback (most recent call last):
  File "C:\github\WPC_Python\core\modules\module_manager.py", line 91, in _load_modules_from_database
    module_id=module.ModuloID,
              ^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\state.py", line 803, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "C:\Users\CarlosT\AppData\Roaming\Python\Python312\site-packages\sqlalchemy\orm\loading.py", line 1603, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Module at 0x1dde929e510> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-07-05 22:58:35 | ERROR    | wpc             | Error inicializando gestor de módulos
